required-players: 1
countdown-seconds: 15
lobby-spawn:
  world: 'world'
  x: 100
  y: 100
  z: 100
  yaw: -180
  pitch: 0
arenas:
  0:
    game: 'BLOCK'
    players-per-team: 1
    max-players: 8
    world-reload-enabled: false
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
  1:
    game: 'PVP'
    players-per-team: 1
    max-players: 8
    world-reload-enabled: false
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
  2:
    game: 'COLORSWAP'
    players-per-team: 1
    max-players: 8
    world-reload-enabled: false
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
  3:
    game: 'TNTWARS'
    players-per-team: 4
    max-players: 8
    world-reload-enabled: false
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
    team-spawns:
      blue:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
      red:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0