required-players: 1
countdown-seconds: 15
lobby-spawn:
  world: 'world'
  x: 100
  y: 100
  z: 100
  yaw: -180
  pitch: 0
victory-podium:
  npc-spawn:
    world: 'world'
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
  player-spawn:
    world: 'world'
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
arenas:
  0:
    game: 'COLORSWAP'
    max-players: 8
    team-size: 1
    world-reload-enabled: false
    npc-spawn:
      world: 'world'
      x: 100
      y: 100
      z: 100
      yaw: -180
      pitch: 0
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
  1:
    game: 'TNTWARS'
    max-players: 16
    team-size: 8
    world-reload-enabled: false
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
    npc-spawn:
      world: 'world'
      x: 100
      y: 100
      z: 100
      yaw: -180
      pitch: 0
    team-spawns:
      blue:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
      red:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
  3:
    game: 'DRAGON_ESCAPE'
    max-players: 4
    team-size: 1
    world-reload-enabled: true
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
    team-spawns:
      blue:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
      red:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
      green:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0
      yellow:
        world: 'world'
        x: 100
        y: 100
        z: 100
        yaw: -180
        pitch: 0