required-players: 1
countdown-seconds: 15
lobby-spawn:
  world: 'world'
  x: 100
  y: 100
  z: 100
  yaw: -180
  pitch: 0
arenas:
  0:
    game: 'BLOCK'
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
  1:
    game: 'PVP'
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0
  2:
    game: 'COLORSWAP'
    world: 'world'
    x: 100
    y: 100
    z: 100
    yaw: -180
    pitch: 0